### ISSUE TITLE
scrollY is reset to 0 on "Edit"

### ISSUE THREAD

**Issue by mvberg** [rsuite/rsuite-table#157]
1. Go here: http://rsuite.github.io/rsuite-table/
2. Select `Editable` scroll to the bottom of the table
3. Click `Edit`

the table jumps back up to the top.

i would expect the row to stay in view. expected?

**Comment by simonguo** [comment]
In order to avoid the wrong position of the scroll bar after data update, the table has a white screen problem, so the position of the scroll bar is automatically reset to 0 after each data update.

You can avoid resetting the scroll bar position by setting `shouldUpdateScroll`.

```jsx
<Table shouldUpdateScroll={false} >
```
If you need to customize the scroll bar position, you can adjust the scroll bar position after the `data` is updated.
```jsx
<Table
  shouldUpdateScroll={false}
  onDataUpdated={(_nextData, scrollTo) => {
    scrollTo({ y: 0, x: 0 });
  }}
>
```

**Comment by mvberg** [comment]
@simonguo thank you, my dude.

amazing work, btw 🚀

**Comment by marcosguti** [comment]
This is still not working I'm using shouldUpdateScroll={false} with virtualization in table but after edit  the cell the vertical scroll still moving to y: 0, some news  about how to fix this?

**Comment by Reggino** [comment]
This bug has been fixed before, but reintroduced since v3.9.4. See [https://codesandbox.io/s/rsuite-table-scroll-demo-f7ijm](https://codesandbox.io/s/rsuite-table-scroll-demo-f7ijm)

**Comment by Reggino** [comment]
I found the fix: you can set the property ```shouldUpdateScroll``` to ```false``` to fix this

**Comment by marcosguti** [comment]
That's weird is not working for me using  shouldUpdateScroll={false } , I'm usign 3.14.3 version, I fixed the issue extending the class rewriting componentDidUpdate lifecycle and removing scroll statement

**Comment by simonguo** [comment]
Please upgrade to the latest rsuite-table.
This issue will be closed, if you have other needs, please open a new one.
